// <auto-generated />
using System;
using Employee_Admin_Portal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_Admin_Portal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622000002_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Employee_Admin_Portal.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("TEXT");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Name").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Phone").HasColumnType("TEXT");
                    b.Property<decimal>("Salary").HasColumnType("TEXT");
                    b.Property<string>("Department").HasColumnType("TEXT");
                    b.Property<string>("JobTitle").HasColumnType("TEXT");
                    b.Property<DateTime>("HiredOn").HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Employee_Admin_Portal.Models.Entities.User", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
                    b.Property<string>("Email").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("TEXT");
                    b.Property<string>("Role").IsRequired().HasColumnType("TEXT");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
